swagger: '2.0'
info:
  title: Blue Banana's Bidder API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /bid:
    post:
      tags: [bids]
      #operationId: app.post_bid
      summary: Request a bid
      parameters:
        - name: bid
          in: body
          schema:
            $ref: '#/definitions/BidReq'
      responses:
        200:
          description: Bid response with a bid
          schema:
            $ref: '#/definitions/BidResp'
        204:
          description: Bid response without a bid

definitions:
  BidReq:
    type: object
    required:
      - id
      - app
      - device
    properties:
      id:
        type: string
        description: The unique identifier of the bid request
        example: "e7fe51ce4f6376876353ff0961c2cb0d"
        readOnly: true
      app:
        type: object
        required:
          - id
          - name
        description: Details about the app where the traffic is coming from
        properties:
          id:
            type: string
            description: The app unique identifier.
            example: "e7fe51ce-4f63-7687-6353-ff0961c2cb0d"
          name:
            type: string
            description: The app name.
            example: "Morecast Weather"  
      device:
        type: object
        required:
          - os
          - geo
        description: Details about the user’s device to which the impression will be delivered
        properties:
          os:
            type: string
            enum: [Android, iOS]
            description: Device operating system.
            example: "Android"
          geo:
            type: object
            required:
              - country
            properties:
              country:
                type: string
                pattern: "^[A-Z]{3}$"
                description: Country code using ISO-3166-1-alpha-3
                example: "USA"
              lat:
                type: number
                description: Latitude from ­90.0 to +90.0, where negative is south
                example: 0
              lon:
                type: number
                description: Longitude from ­180.0 to +180.0, where negative is west
                example: 0  
  BidResp:
    type: object
    required:
      - id
      - bid
    properties:
      id:
        type: string
        description: The unique identifier of the bid request
        example: "e7fe51ce4f6376876353ff0961c2cb0d"
        readOnly: true
      bid:
        type: object
        required:
          - campaignId
          - price
          - adm
        description: Information about the bid
        properties:
          campaignId:
            type: string
            description: The campaign id.
            example: "5a3dce46"
          price:
            type: number
            description: The bid price.
            example: 1.2 
          adm:
            type: string
            description: The ad markup.
            example: "<a href=\"http://example.com/click/qbFCjzXR9rkf8qa4\"><img src=\"http://assets.example.com/ad_assets/files/000/000/002/original/banner_300_250.png\" height=\"250\" width=\"300\" alt=\"\"/></a><img src=\"http://example.com/win/qbFCjzXR9rkf8qa4\" height=\"1\" width=\"1\" alt=\"\"/>"     
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
